### current user
GET https://ticketing.dev/api/users/currentuser

### sign up
POST  https://ticketing.dev/api/users/signup
Content-Type: application/json

{
  "email": "123@123.com",
  "password": "123123"
}

### sign in
POST https://ticketing.dev/api/users/signin
Content-Type: application/json

{
  "email": "123@123.com",
  "password": "123123"
}

### ----------------------------------------------

### create a ticket
POST https://ticketing.dev/api/tickets
Content-Type: application/json

{
  "title": "ticket-3",
  "price": 30
}

### fetch tickets
GET https://ticketing.dev/api/tickets

### update a ticket
PUT https://ticketing.dev/api/tickets/61363b072c1e380019bb3052
Content-Type: application/json

{
  "title": "ticket-1-m3",
  "price": 33
}



### ----------------------------------------------
### [Orders-Services]
### =================
### fetch orders
GET https://ticketing.dev/api/orders

### create a order
POST https://ticketing.dev/api/orders
Content-Type: application/json

{
  "ticketId": "61363d2b2c1e380019bb305d"
}
