### current user
GET https://ticketing.dev/api/users/currentuser

### sign up
POST  https://ticketing.dev/api/users/signup
Content-Type: application/json

{
  "email": "123@123.com",
  "password": "123123"
}

### sign in
POST https://ticketing.dev/api/users/signin
Content-Type: application/json

{
  "email": "123@123.com",
  "password": "123123"
}

### ----------------------------------------------

### create a ticket
POST https://ticketing.dev/api/tickets
Content-Type: application/json

{
  "title": "ticket - 3",
  "price": 59.99
}

### fetch tickets
GET https://ticketing.dev/api/tickets

### update a ticket
PUT https://ticketing.dev/api/tickets/612fa4aa091ec5001b77bc25
Content-Type: application/json

{
  "title": "ticket - 1-1",
  "price": 30
}


### ----------------------------------------------

### fetch tickets
GET https://ticketing.dev/api/orders
